# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  desktop:
    taskfile: ./desktop/Taskfile.yml
    dir: ./desktop
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true
