version: '3'

vars:
  BINARY_NAME: broker
  BINARY_DIR: ./bin

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the broker binary
    cmds:
      - go build -o {{.BINARY_DIR}}/{{.BINARY_NAME}} ./cmd/broker
    sources:
      - ./**/*.go
    generates:
      - '{{.BINARY_DIR}}/{{.BINARY_NAME}}'

  run:
    desc: Run the broker (builds first if needed)
    deps: [build]
    env:
      PORT: '{{.PORT | default "8080"}}'
      LOG_LEVEL: '{{.LOG_LEVEL | default "debug"}}'
    cmds:
      - '{{.BINARY_DIR}}/{{.BINARY_NAME}}'

  dev:
    desc: Run with auto-reload (requires air)
    cmds:
      - air

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  test:integration:
    desc: Run integration tests
    cmds:
      - go test -v -race ./tests/integration/...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BINARY_DIR}}

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
